version: '3.3'
services:
  web:
    env_file:
      - .env
  linklives-api:
    container_name: linklives-api
    image: 282251075226.dkr.ecr.eu-west-1.amazonaws.com/linklives-api:{image-tag}
    ports: 
      - "4201:80"
  linklives-usermanagement-api:
    container_name: linklives-usermanagement-api
    image: 282251075226.dkr.ecr.eu-west-1.amazonaws.com/linklives-usermanagement-api:{image-tag}
    ports: 
      - "4202:80"