// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using linklives_api_dal;

namespace linklives_api_dal.Migrations
{
    [DbContext(typeof(LinklivesContext))]
    [Migration("20210416103713_LinkRatingKey")]
    partial class LinkRatingKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("linklives_api_dal.domain.LifeCourse", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("Life_course_id")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("LifeCourses");
                });

            modelBuilder.Entity("linklives_api_dal.domain.Link", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("Iteration")
                        .HasColumnType("int");

                    b.Property<int>("Iteration_inner")
                        .HasColumnType("int");

                    b.Property<string>("LifeCourseKey")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("Link_id")
                        .HasColumnType("int");

                    b.Property<string>("Method_description")
                        .HasColumnType("text");

                    b.Property<int>("Method_id")
                        .HasColumnType("int");

                    b.Property<string>("Method_subtype1")
                        .HasColumnType("text");

                    b.Property<string>("Method_type")
                        .HasColumnType("text");

                    b.Property<int>("Pa_id1")
                        .HasColumnType("int");

                    b.Property<int>("Pa_id2")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("double");

                    b.Property<int>("Source_id1")
                        .HasColumnType("int");

                    b.Property<int>("Source_id2")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasIndex("LifeCourseKey");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("linklives_api_dal.domain.LinkRating", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("Description")
                        .HasColumnType("int");

                    b.Property<string>("LinkKey")
                        .HasColumnType("varchar(767)");

                    b.Property<bool>("Rating")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Key");

                    b.HasIndex("LinkKey");

                    b.ToTable("LinkRatings");
                });

            modelBuilder.Entity("linklives_api_dal.domain.Link", b =>
                {
                    b.HasOne("linklives_api_dal.domain.LifeCourse", "LifeCourse")
                        .WithMany("Links")
                        .HasForeignKey("LifeCourseKey");

                    b.Navigation("LifeCourse");
                });

            modelBuilder.Entity("linklives_api_dal.domain.LinkRating", b =>
                {
                    b.HasOne("linklives_api_dal.domain.Link", "Link")
                        .WithMany("Ratings")
                        .HasForeignKey("LinkKey");

                    b.Navigation("Link");
                });

            modelBuilder.Entity("linklives_api_dal.domain.LifeCourse", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("linklives_api_dal.domain.Link", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
